# Site settings
title: Pick Me Up
email: pickmeupbot@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 PickMeUp è un servizio di carpooling dinamico che funziona via Telegram. Il servizo è totalmente gratuito. 

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pickmeup.trentino.it" # the base hostname & protocol for your site

twitter_username: PickMeup_bot
github_username:  kercos/PickMeUp
facebook_username: example

###############
# Life Events #
###############
# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.jpg"

# User setting
owner: Angelo Basile

address:
  - line: 3481 Melrose Hill St
  - line: "Los Angeles, CA 90029"
  # Feel free to add more lines here 
copyright: PickMeUp

# API settings
google_api_key: AIzaSyA8H0jVz_6Hc273rqNYKQ6AAiBvQfVKmYQ

# Build settings
markdown: kramdown
