# Site settings
title: Pick Me Up
email: pickmeupbot@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 PickMeUp è un servizio di carpooling dinamico che funziona via Telegram. Il servizo è totalmente gratuito. 

baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: PickMeup_bot
github_username:  kercos/PickMeUp

# Build settings
markdown: kramdown
